#!/usr/bin/env bash
if [ "$#" -lt 3 ]
    then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
path="$1"
ip="$2"
username="$3"
ssh_path="$4"
scp -i "$ssh_path" -o StrictHostKeyChecking=no "$path" "$username""@""$ip:~/" 
