#!/usr/bin/env bash
# Installing Nginx web server on a remote server.
sudo su
apt-get update && apt-get -y install nginx 
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
