#!/usr/bin/env bash
# Installing Nginx web server on a remote server.
sudo su
apt-get update && apt-get -y install nginx 
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/s/listen *[0-9]\+;/listen 80;/g" /etc/nginx/sites-available/default
