#!/usr/bin/env bash
# Installing Nginx on `web-01` server.
# Making the Nginx server listen on port 80.
sudo su
apt-get update && sudo apt-get install nginx -y
sed -i '/s/listen [0-9]\+;/listen 80;/g' /etc/nginx/sites-enabled/default
sed -ie "server_name emaracodes.tech;\n rewrite ^/redirect_me "\
    "https://www.youtube.com/watch?v=QH2-TGUlwu4\ permenant;"
sed -ie "/s/server_name/${word}/g" /etr/nginx/sites-enabled/default
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx restart
