#!/usr/bin/env bash
# Configuring the Nginx web server's `/redirect_me`
# to redirect to another page.
sudo su
sudo apt-get update && sudo apt-get -y install nginx 
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/\(listen \[::\]:80 default_server;\)/\1\n\trewrite ^\/redirect_me https\:\/\/google\.com\/ permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
