#!/usr/bin/env bash
# Configuring the Nginx web server's `/redirect_me`
# to redirect to another page.
sudo apt-get update && sudo apt-get -y install nginx 
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/listen \[\:\:\]\:80 default_server;/a \\\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
