#!/usr/bin/env bash
# Configuring the Nginx web server's `/redirect_me`
# to redirect to another page and the `error 404` page.
sudo apt-get update && sudo apt-get -y install nginx 
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i "/listen \[\:\:\]\:80 default_server;/a \\\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/permanent;/a \\\terror_page 404 /error404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
