#!/usr/bin/env bash
# Installing an HAproxy on the `lb-01` server and configuring it.
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "CONFIG=/etc/haproxy/haproxy.cfg" | sudo tee -a /etc/default/haproxy

echo "
frontend front-web
	mode http
	bind *:80
	default_backend back-web

backend back-web
	balance roundrobin
	mode http
	server 187237-web-01 18.235.243.33:80 check
	server 187237-web-02 54.237.84.225:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
# Run the following command to debug.
#haproxy -f /etc/haproxy/haproxy.cfg -c
