#!/usr/bin/env bash
# Configuring Nginx web server to listen to port 80, then stop running.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx stop
