#!/usr/bin/env bash
# Printing all process for all users, including processes without TTY
#+ while displaying it  in user-oriented format,
#+ and showing process hierarchy.
#+ where it includes (USER,PID,%CPU,%MEM,VSZ,RSS,TTY,STAT,START,TIME,COMMAND).
ps u -AH
