#!/usr/bin/env bash
# Printing "bad luck" if the iteration no. is 4
#+ and "good luck" if the iteration no. is 8
#+ and "Best School" otherwise, using while loop and
#+ if, elif, and else control flow statments.
i="1"
while [ $i -ne 11 ]; do
    if [ $i -eq 8 ]
    then
        echo "good luck"
    elif [ $i -eq 4 ]
    then
        echo "bad luck"
    else
        echo "Best School"
    fi
    ((i++))
done
