#!/usr/bin/env bash
# Printing hours from 0 to 12 hours, and
#+ minutes from 1 to 59 using while loop.
hours="0"
mins="1"
while [ $hours -le 12 ]; do
    echo "Hour: $hours"
    while [ $mins -le 59 ]; do
        echo $mins
        ((mins++))
    done
    if [ $mins -ne 59 ]
    then
        mins=1
    fi
    ((hours++))
done
