#!/usr/bin/env bash
# Displaying information about the "school" file.
#+ 1. Checks if the file exists,
#+ 2. If it exists: empty or not empty.
#+                  regular or not regular.
if [ -e "school" ]; then
    echo "school file exists"
    if [ -s "school" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "school" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
