#!/usr/bin/env bash
# Installing `ufw` firewall and setting up the firewall rules.
# Installing `ufw` firewall.
sudo apt install ufw -y
# Denying all incoming connections and allowing all outgoing connections.
sudo ufw default deny incoming && sudo ufw default allow outgoing
# Allowing incoming connections via port 22 (SSH).
sudo ufw allow 22
# Allowing incoming connections via port 443 (HTTPS SSL).
sudo ufw allow 443
# Allowing incoming connectionsw via port 80 (HTTP).
sudo ufw allow 80
# Redirecting traffic from port 8080 to port 80.
sudo sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw
sudo echo "\
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
COMMIT" | sudo tee /etc/ufw/before.rules
# Enabling the `ufw` firewall.
echo "y" | sudo ufw disable
echo "y" | sudo ufw enable
# Checking on the `ufw` firewall rules.
# sudo ufw status verbose
