#!/usr/bin/env bash
# Resolving localhost to 127.0.0.1 and
#+ facebook to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i "s/127.*$/127.0.0.2       localhost/" ~/hosts.new
echo "8.8.8.8       facebook.com" >> ~/hosts.new
cp ~/hosts.new /etc/hosts
