#!/usr/bin/env bash
# Making Nginx running as the `nginx` user.
sudo sed -i "s/\#user www\-data/user nginx nginx/g" /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /etc/nginx
sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/www/html
sudo chown -R nginx:nginx /var/lib/nginx
sudo sed -i "s/listen 80/listen 8080/g" /etc/nginx/sites-available/default
sudo sed -i "s/listen \[\:\:\]\:80/listen \[\:\:\]\:8080/g" /etc/nginx/sites-available/default
sudo netstat -tulpn | grep :8080 | awk -F " " '{print $7}' | awk -F "/" '{print $1}' | xargs kill
sudo -u nginx service nginx restart
