#!/usr/bin/env bash
# Using `SSH` protocol to connect to the server using the private key
# ~/.ssh/school with the user ubuntu.
cp ~/.ssh/id_rsa ~/.ssh/school
ssh -i ~/.ssh/school ubuntu@18.235.243.33
