#!/usr/bin/env bash
# Creating an RSA key pair. Where the private key must be `school`;
# Number of bits in the created key is 4096, and the created key
# must be protected by the passphrase `betty`.
ssh-keygen -b 4096 -f 'school' -N 'betty'
